# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-09 06:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutodeskAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=256)),
                ('firstname', models.CharField(max_length=32)),
                ('lastname', models.CharField(max_length=32)),
                ('profileimage_s', models.CharField(max_length=1024)),
                ('profileimage_m', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='ContentsCashe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hubid', models.CharField(max_length=256)),
                ('itemid', models.CharField(max_length=256)),
                ('parentid', models.CharField(max_length=256)),
                ('text', models.CharField(max_length=64)),
                ('icon', models.CharField(max_length=64)),
                ('lastModifiedTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='date posted')),
            ],
        ),
    ]
